[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "HsnxgoaXUn33tifeS3S2v9QY2uAm292Buc1Qjx13d9dY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/rayturla/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
